# Generated by Django 4.0.4 on 2022-07-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_watchlist_list_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='creater',
        ),
    ]
